### PR TITLE
Render Docs in a Webpage

### PR DESCRIPTION
**Pull request by keenanjohnson**
This change does a few things to improve the documentation experience of building a Frog Sensor.

It adds a step to build the Markdown files as a webpage which includes a nicer table of contents, loads faster, and looks better on mobile. This is implemented using [MKDocs Material.](https://squidfunk.github.io/mkdocs-material/)

It also removes all the V1->V3 docs and Frog files as those are not really useful any longer.

A preview of the site can be seen here: https://ribbit-network.github.io/ribbit-network-frog-hardware/pr-preview/pr-218/

### CODE REVIEW

**Comment by keenanjohnson** [comment]
@eaudiffred and @pascaljoly I've been working on this improvement to the docs. It renders the docs into a nice website that you can see a [preview of here.](https://ribbit-network.github.io/ribbit-network-frog-hardware/pr-preview/pr-218/)

Would love any thoughts if you think this is an improvement!

**Comment by keenanjohnson** [comment]
Image of the new site: 
image

**Comment by keenanjohnson** [comment]
And here is a video of the new docs on mobile: 
https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/2559382/403105b8-af76-42e1-a961-63197818f976

**Comment by pascaljoly** [comment]
Looks great. There seem to be a missing link here: All of the parts from Adafruit can be found in this wishlist: 
https://ribbit-network.github.io/ribbit-network-frog-hardware/pr-preview/pr-218/1-parts/1-parts/￼

**Comment by pascaljoly** [comment]
Another comment: on the printing materials. It would be good to mention about recycled plastic option for the filament
Given that the sensors are designed to sit outside, a PETG 3D Printer Filament should be used for all the parts. 
https://ribbit-network.github.io/ribbit-network-frog-hardware/pr-preview/pr-218/2-3d-printing/2-3d-printing/￼

**Comment by keenanjohnson** [comment]
Thanks @pascaljoly ! I've fixed that link and we already have a note on PETG in the 3D printing section:

image

**Comment by keenanjohnson** [comment]
Any comments or feedback from you @eaudiffred or do we think this is good to merge?

**Comment by eaudiffred** [comment]
@keenanjohnson Looks great!  I did notice that the BOM link and the 3D printed parts file link are not working.  

Overall this is way easier to read and follow along!

**Comment by keenanjohnson** [comment]
Oh let me check on that. It may be sort of due to how the preview is rendering.

Thanks @eaudiffred !

**Comment by keenanjohnson** [comment]
Yeah those links are just broken due to the preview plugin I have. I have verified they work locally.

Merging now!

**Pull request merged**
