### PR TITLE
[WIP] Gps exploration

### PR DESCRIPTION
**Pull request by akhilgupta1093**

### CODE REVIEW

**Comment by keenanjohnson** [comment]
When I attempt to run this on my device I get the following error:

```
I (15183) frog_sensor: Initializing the device
Failed to parse the sentence!
  Type: PMTK0 (0)
Failed to parse the sentence!
  Type: PMTK0 (0)
Failed to parse the sentence!
  Type: PMTK0 (0)
GPRMC sentence
  Longitude: 0, Latitude: 0
I (15263) frog_sensor: SCD30 Firmware Version: 3.2
I (15263) frog_sensor: Starting continuous measurement
E (16183) golioth_coap_client: DNS lookup failed for destination ainfo coap.golioth.io. error: 202
I (16183) golioth_coap_client: Ending session
E (16263) i2cdev: Could not take port mutex 0ESP_ERROR_CHECK failed: esp_err_t 0x107 (ESP_ERR_TIMEOUT) at 0x4037cfac
0x4037cfac: _esp_error_check_failed at /Users/keenan/esp/esp-idf/components/esp_system/esp_err.c:42

file: "./main/app_main.c" line 75
func: scd30_task
expression: scd30_trigger_continuous_measurement(&dev, 0)

abort() was called at PC 0x4037cfaf on core 1
0x4037cfaf: _esp_error_check_failed at /Users/keenan/esp/esp-idf/components/esp_system/esp_err.c:43



Backtrace:0x40375c76:0x3fca49f00x4037cfb9:0x3fca4a10 0x40384c5a:0x3fca4a30 0x4037cfaf:0x3fca4aa0 0x42007639:0x3fca4ac0 0x40380d15:0x3fca4b30 
0x40375c76: panic_abort at /Users/keenan/esp/esp-idf/components/esp_system/panic.c:402

0x4037cfb9: esp_system_abort at /Users/keenan/esp/esp-idf/components/esp_system/esp_system.c:128

0x40384c5a: abort at /Users/keenan/esp/esp-idf/components/newlib/abort.c:46

0x4037cfaf: _esp_error_check_failed at /Users/keenan/esp/esp-idf/components/esp_system/esp_err.c:43

0x42007639: scd30_task at /Users/keenan/Documents/GitHub/ribbit-network-frog-sensor/v4/software/main/app_main.c:75 (discriminator 1)

0x40380d15: vPortTaskWrapper at /Users/keenan/esp/esp-idf/components/freertos/port/xtensa/port.c:131
```

**Comment by keenanjohnson** [comment]
Interestingly it seemed to start working later after a few reboots. It seems like there must be a race condition initializing the I2C port per that error message above that sometimes works out.

Did you see this at all during your testing @akhilgupta1093 ?

**Comment by keenanjohnson** [comment]
Ok I think I see what is happening maybe. The other two sensors SCD30 and DS310 come from https://github.com/UncleRus/esp-idf-lib.

All of their i2c functions (read, write, etc) use these i2c helper functions from this subfolder in that project: https://github.com/UncleRus/esp-idf-lib/blob/master/components/i2cdev/i2cdev.h

For example, see the read function in the dps310 driver.

https://github.com/UncleRus/esp-idf-lib/blob/0b8a3a55802d367d7865af0bcbca9ac3cb993bdf/components/dps310/src/helper_i2c.c#L83-L95

Those functions use the helper function I2C_DEV_TAKE_MUTE, etc.

This is apparently because the default i2c driver in esp-idf is not thread safe (meaning it can cause issues if our concurrent threads are accessing it at the same time). 

So I think the way to fix this would be to adapt the gps driver to use the same mutex helper functions used by the SCD30 and DPS310 devices. 

This is a bit complicated though, and given we don't exactly plan on running this code, I'll leave it up to you whether you would like to fix this now or leave some comments as fixme for us or whoever comes in the future @akhilgupta1093 .

**Comment by akhilgupta1093** [comment]
@keenanjohnson Oh gosh, thanks for finding that out. I've just added some comments disclaiming the issue. If we need to cross this bridge sometime in the future, I'm happy to re-take this on.

**Review by keenanjohnson — APPROVED** [review]
Looks good for now. We don't really plan on using this code at the moment, but good for potential reference in the future.

**Pull request merged**
